# Generated by Django 5.0.6 on 2024-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disk_space', models.IntegerField()),
                ('email_accounts', models.IntegerField()),
                ('support', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
