# Generated by Django 5.0.6 on 2024-06-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pricing_delete_pricingplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
