# Generated by Django 5.0.6 on 2024-06-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
